@host = http://localhost:3001

POST {{ host }}/auth/signup/ HTTP/1.1
Content-Type: 'application/json'

{
    "username": "chosen",
    "password": "creains1",
    "role": "normal"
}
###

POST {{ host }}/auth/signup/ HTTP/1.1
Content-Type: 'application/json'

{
    "username": "abcde",
    "password": "dodcvdsdve",
    "role": "admin"
}
###

POST {{ host }}/auth/login/ HTTP/1.1
Content-Type: 'application/json'

{
    "username": "john",
    "password": "doe"
}
###

POST {{ host }}/auth/login/ HTTP/1.1
Content-Type: 'application/json'

{
    "username": "ehab",
    "password": "abcdefghilmn"
}
###

POST {{ host }}/auth/verify/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiY2hvc2VuIiwiaWQiOjYsInJvbGUiOiJub3JtYWwiLCJvcGVyYXRpb25zIjpbInJlYWQiXSwiaWF0IjoxNzI2MTI1MzkxfQ.CbC1tkx-_iJTNXmfOfvtkTY2R2VkPSDlXXQPewnDAQU

{
}
###

POST {{ host }}/auth/verify/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZWhhYiIsImlkIjo4LCJyb2xlIjoiYWRtaW4iLCJvcGVyYXRpb25zIjpbInJlYWQiLCJ3cml0ZSIsImRlbGV0ZSJdLCJpYXQiOjE3MjYxMzMxMzksImV4cCI6MTcyNjIxOTUzOX0.il1dHeCLVhBHk3aJwBWQbA2tWLO-TYTywGq7D5UhMSI

{
}
###